# Multi-stage build for Laravel + Vue + Inertia application

# Stage 1: Build frontend assets
FROM node:22-alpine AS node-builder

WORKDIR /app

# Install PHP and required extensions for wayfinder plugin
RUN apk add --no-cache \
    php82 \
    php82-cli \
    php82-openssl \
    php82-phar \
    php82-mbstring \
    php82-xml \
    php82-dom \
    php82-tokenizer \
    php82-json \
    php82-pdo \
    php82-pdo_sqlite \
    sqlite \
    && ln -s /usr/bin/php82 /usr/bin/php

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy package files
COPY package*.json ./

# Install Node.js dependencies
RUN npm ci --only=production=false

# Copy application files
COPY . .

# Install PHP dependencies
RUN set -e; \
    if ! composer install --no-interaction --prefer-dist --no-scripts --ignore-platform-reqs; then \
        echo "Updating composer dependencies..."; \
        composer update --no-interaction --prefer-dist --no-scripts --ignore-platform-reqs; \
    fi

# Set up Laravel environment (copy from .env.example if .env doesn't exist)
RUN if [ ! -f .env ] && [ -f .env.example ]; then \
        cp .env.example .env; \
    fi

# Create required directories
RUN mkdir -p bootstrap/cache \
    storage/framework/{cache/data,sessions,views} \
    storage/logs \
    resources/js/{wayfinder,routes,actions} \
    /tmp \
    && touch /tmp/database.sqlite \
    && chmod -R 775 bootstrap/cache storage /tmp

# Discover packages and optimize
RUN php artisan package:discover --ansi && \
    composer dump-autoload --optimize --classmap-authoritative

# Build frontend assets (wayfinder will be generated by vite plugin)
RUN npm run build

# Stage 2: PHP production image with Nginx and PHP-FPM
FROM php:8.2-fpm

WORKDIR /app

# Install system dependencies and PHP extensions
RUN apt-get update && apt-get install -y \
    git \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    libzip-dev \
    nginx \
    supervisor \
    && docker-php-ext-install pdo_mysql pdo mbstring exif pcntl bcmath gd zip \
    && pecl install redis \
    && docker-php-ext-enable redis \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Install Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Copy composer files and install dependencies
COPY --chown=www-data:www-data composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --prefer-dist --no-scripts

# Copy application files
COPY --chown=www-data:www-data . .

# Copy built assets
COPY --from=node-builder --chown=www-data:www-data /app/public/build ./public/build

# Optimize Laravel
RUN composer dump-autoload --optimize --classmap-authoritative && \
    php artisan package:discover --ansi

# Copy supervisor and nginx configuration files
COPY --chown=root:root docker/assets/ /assets/

# Set up directories and permissions
RUN mkdir -p /var/log /etc/supervisor/conf.d/ && \
    touch /var/log/nginx-access.log /var/log/nginx-error.log && \
    chown -R www-data:www-data /var/log /app && \
    chmod -R 755 /app && \
    chmod -R 775 /app/storage /app/bootstrap/cache && \
    chmod +x /assets/start.sh && \
    cp /assets/worker-*.conf /etc/supervisor/conf.d/

EXPOSE 80

HEALTHCHECK --interval=30s --timeout=3s --start-period=40s --retries=3 \
    CMD curl -f http://localhost:${PORT:-80}/ || exit 1

CMD ["/assets/start.sh"]
